# Generated by Django 2.1.7 on 2019-05-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190327_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image_url',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='image.jpeg', upload_to='images/'),
        ),
    ]
